server:
  port: 1001
  context-path: /
 

eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: microservice-student
    instance-id: microservice-student:1001 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
      #集群远程defaultZone: http://eureka2001.java1234.com:2001/eureka/,http://eureka2002.java1234.com:2002/eureka/,http://eureka2003.java1234.com:2003/eureka/ # 集群

      
info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   负责人: 张三
   联系电话: 110